version: '3.4'

services:
  deepreinforcementlearning:
    image: deepreinforcementlearning
    build:
      context: .
      dockerfile: ./Dockerfile
    command: ["sh", "-c", "pip install debugpy -t /tmp && python /tmp/debugpy --wait-for-client --listen 0.0.0.0:5678 p2_continuous-control/main.py "]
    ports:
      - 5678:5678
